### ISSUE TITLE
Arduino Example Fails to Compile

### ISSUE THREAD

**Issue by rei-vilo** [Losant/losant-docs#24]
The example detailed at [Getting Started with the Arduino WiFi 101 Shield](https://docs.losant.com/getting-started/boards/getting-started-with-arduino-wifi-101/#getting-started-with-the-arduino-wifi-101-shield) is confused, as it mixes two or even three different applications. 

* Connecting to Losant
* Sending State
* Receiving Commands

Moreover, it doesn't correspond to the `arduino-wifi-shield-101.ino` [code](https://github.com/Losant/losant-mqtt-arduino/blob/master/examples/arduino-wifi-shield-101/arduino-wifi-shield-101.ino).

Compiling against the Arduino Zero with Arduino IDE 1.6.12 fails.

>
>    JsonObject & payload = command->payload;
>
>invalid initialization of reference of type 'ArduinoJson::JsonObject&' from expression of type 'ArduinoJson::JsonObject*'
>

**Comment by anaptfox** [comment]
@rei-vilo thanks for the catch! I'll dig in and update these instructions here soon.

**Comment by rei-vilo** [comment]
I'm trying to use the same example on the [LaunchPad CC3200](http://www.ti.com/tool/cc3200-launchxl) but I'm facing identification issues. The IDE is [Energia](http://energia.nu), based on the same Arduino / Wiring framework.

I've triple-checked `Device ID`, `Access Key`and `Access Secret`, to no avail. 

The only parameter I haven't mentioned in `Application ID`.

**Comment by rei-vilo** [comment]
It looks like that `JsonObject& payload = *command->payload;` does the trick.
