### ISSUE TITLE
Example for mosquitto_pub

### ISSUE THREAD

**Issue by rei-vilo** [Losant/losant-docs#26]
I'm trying to use the command-line `mosquitto_pub` to test the connection with Losant.

`mosquitto_pub -h broker.losant.com -p 1883 -t losant/$LOSANT_DEVICE_ID/state -m '{"data":{"Light":3.40e4,"Temperature":24.86,"Humidity":63.05,"Pressure":1.03e3}}' --key $LOSANT_ACCESS_KEY --cert $LOSANT_ACCESS_SECRET`

>Connection Refused: not authorised.
>Error: The connection was refused.

What is possibly wrong?

**Comment by spacetc62** [comment]
@rei-vilo the key/secret are not a certificate pair, they are the username/password as described here: https://docs.losant.com/mqtt/overview/#authentication - these will be the --username and --pw arguments on mosquitto_pub. In addition, you need to set your device id as the mqtt client id (the --id argument on mosquitto_pub).

I'd recommend that if you have more questions, you should check out our forums at https://forums.losant.com/ and post questions there!

**Comment by InconceivableDuck** [comment]
Here's a working example I put together to show the syntax:

```
mosquitto_pub -h broker.losant.com -p 1883 -i MY_DEVICE_ID -u "MY_ACCESS_KEY" -P "MY_ACCESS_SECRET" -t "losant/MY_DEVICE_ID/state" -m '{ "data" : { "temp" : 30.0 }}'
```

**Comment by rei-vilo** [comment]
Thank you!
